package com.gridx.event;

public enum EventType {
    ENERGY_GENERATED, ENERGY_CONSUMED, ENERGY_SHORTAGE, ENERGY_SURPLUS,
    BATTERY_CHARGED, BATTERY_DISCHARGED, MARKET_ORDER_CREATED, TRADE_EXECUTED,
    GRID_CONGESTION, POWER_PLANT_FAILED, BLACKOUT_WARNING, LOAD_DISCONNECTED,
    LOAD_RESTORED, EV_CHARGING_STARTED, EV_CHARGING_COMPLETED, PRICE_CHANGED,
    SIMULATION_STARTED, SIMULATION_PAUSED, SIMULATION_RESUMED, SIMULATION_STOPPED,
    FAILURE_INJECTED, GRID_BALANCED, MARKET_CLEARED, BLACKOUT, RECOVERY_INITIATED
}
